apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- vpa.yaml

patches:
- path: patches/resource-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: example-app
    version: v1
