apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: vpa-recommender
type: Opaque
data:
  # Replace with your actual token
  token: TOKEN
---
apiVersion: recommander.k8s.io/v1
kind: VPARecommender
metadata:
  name: example-recommender
  namespace: vpa-recommender
spec:
  vpaName: example-app-vpa
  vpaNamespace: default
  gitRepo: "https://github.com/Thaliph/vparecommander.git"
  gitPath: "examples/kustomize-example"
  targetResource:
    kind: Deployment
    name: example-app
    namespace: default
    containerIndex: 0
  secretRef: git-credentials
