apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: vpa-recommender
type: Opaque
data:
  # Fixed token without newlines
  token: TOKEN

---
apiVersion: recommander.k8s.io/v1
kind: VPARecommender
metadata:
  name: example-recommender
  namespace: vpa-recommender
spec:
  vpaName: example-app-vpa  # Updated to match the VPA name
  vpaNamespace: default
  gitRepo: "https://github.com/Thaliph/vparecommander.git"
  gitPath: "examples/kustomize-example"
  targetResource:
    kind: Deployment
    name: example-app  # Updated to match the deployment name
    namespace: default
    containerIndex: 0
  secretRef: git-credentials
