apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vparecommenders.recommander.k8s.io
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes/kubernetes/pull/78458"
spec:
  group: recommander.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                vpaName:
                  type: string
                  description: "Name of the VerticalPodAutoscaler resource to read recommendations from"
                vpaNamespace:
                  type: string
                  description: "Namespace of the VerticalPodAutoscaler resource"
                gitRepo:
                  type: string
                  description: "Git repository URL"
                gitPath:
                  type: string
                  description: "Path within the git repository where patches should be stored"
                baseBranch:
                  type: string
                  description: "Base branch for pull requests (defaults to main)"
                  default: "main"
                targetResource:
                  type: object
                  description: "Resource that will be patched"
                  properties:
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                    containerIndex:
                      type: integer
                      default: 0
                secretRef:
                  type: string
                  description: "Name of the secret containing Git credentials"
              required:
                - vpaName
                - vpaNamespace
                - gitRepo
                - gitPath
                - targetResource
                - secretRef
            status:
              type: object
              properties:
                lastRecommendation:
                  type: object
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                lastPatch:
                  type: object
                  properties:
                    time:
                      type: string
                    path:
                      type: string
                    target:
                      type: string
                pullRequest:
                  type: object
                  properties:
                    url:
                      type: string
                    number:
                      type: integer
                    created_at:
                      type: string
                    commits:
                      type: integer
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
      subresources:
        status: {}  # Adding status subresource to properly handle status updates
  scope: Namespaced
  names:
    plural: vparecommenders
    singular: vparecommender
    kind: VPARecommender
    shortNames:
    - vpar
